import type { Metadata } from "next"

import Navbar from "@/components/layout/navbar/Navbar"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="sunset">
      <body>
        <Navbar />
        <main className="container-wrapper py-8">{children}</main>
      </body>
    </html>
  )
}
